dbus_config: Remove dbus configuration file
The same copy of the default dbus configuration file can be found in
https://github.com/GENIVI/persistence-client-library and that should be
the only repository holding this file.

Furthermore, because this file is being installed by both of these
components, the Yocto build system will declared the do_rootfs job as a
failure due to the following error:

Error: Transaction check error:
  file /etc/dbus-1/system.d/org.genivi.persistence.admin.conf conflicts
  between attempted installs of persistence-client-library-1.1.0 and
  libpers-common0-1.0.3

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>